### signup
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "userId": "avocado",
    "password": "4444",
    "name": "안카도",
    "phone": "010-4444-4444",
    "memberType": "ROLE_USER"
}

### signin
POST http://localhost:8080/user/signin
Content-Type: application/json

{
    "userId": "avocado",
    "password": "4444"
}