### signup
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "userId": "admin",
    "password": "8888",
    "name": "관리자",
    "phone": "010-8888-8888",
    "memberType": "ROLE_PARTNER"
}

### signin
POST http://localhost:8080/user/signin
Content-Type: application/json

{
    "userId": "admin",
    "password": "8888"
}

### delete member
DELETE http://localhost:8080/user/13
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTkwODE2NzQsImV4cCI6MTY5OTA4NTI3NH0.BkvJjpeQoWnrTtBrEWMVW3XKIudGJyA1pdVVABZTKEwsynVPy2Q_UOVftPqfiPjhnzydYDUV0rVBm4gIqBus6g