### signup
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "userId": "abc",
    "password": "7777",
    "name": "알파벳",
    "phone": "010-7777-7777",
    "memberType": "ROLE_PARTNER"
}

### signin
POST http://localhost:8080/user/signin
Content-Type: application/json

{
    "userId": "melon",
    "password": "4444"
}

### delete member
DELETE http://localhost:8080/user/delete/9