### reserve store
POST http://localhost:8080/reservation/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJvcmFuZ2UiLCJtZW1iZXJUeXBlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjk4MjEzNDIxLCJleHAiOjE2OTgyMTcwMjF9.44MLGujK5zjHdKGmkAVe-QhQ70mpTkTIQPGTMK7YVA_DbpcobDgB7K0zohblLCkGltpkbDiHs5Fs_Eko7qSTow

{
    "reservationDate": "2023-10-23T12:00:00"
}

### get reservationList (User)
GET http://localhost:8080/reservation/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiYW5hbmEiLCJtZW1iZXJUeXBlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjk4MjEyMDY5LCJleHAiOjE2OTgyMTU2Njl9.bUm_WQ_kCTfyIWnccPRKI1O73Ia3UBPs7V783VqgvEvgdR8QdAL3u8ABn9PNGuSgNYl2XHpB7Vu5JOFxcJOK1A

### get reseravtionList (Partner)
GET http://localhost:8080/reservation/list/7?date=2023-10-23
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZWxvbiIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTgyMTQ5NDQsImV4cCI6MTY5ODIxODU0NH0.25OmK4TMq0VgfMPPQ40Sn50ZfH5OpP4NMNuRaLHCRL25WHRc4onKa2s2EgpcCMHoYNnTtQ4E0khDNDEfHpfk5Q

### approve reservation
PATCH http://localhost:8080/reservation/approval/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjaGVycnkiLCJtZW1iZXJUeXBlIjoiUk9MRV9QQVJUTkVSIiwiaWF0IjoxNjk4MjEzNTgyLCJleHAiOjE2OTgyMTcxODJ9.CtZEXjcEwaM4b36wpM-_cJIq9hWW_dcPOVxPB_QIQIdvAVVxbBHgGCMwNPcwSjUIfEf2MFQbfIOewwByWaEA_w


### approve reservation
PATCH http://localhost:8080/reservation/refusal/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZWxvbiIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTgyMTQ5NDQsImV4cCI6MTY5ODIxODU0NH0.25OmK4TMq0VgfMPPQ40Sn50ZfH5OpP4NMNuRaLHCRL25WHRc4onKa2s2EgpcCMHoYNnTtQ4E0khDNDEfHpfk5Q