### reserve store
POST http://localhost:8080/reservation/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZWxvbiIsIm1lbWJlclR5cGUiOiJST0xFX1VTRVIiLCJpYXQiOjE2OTg1ODY1NjEsImV4cCI6MTY5ODU5MDE2MX0.-Nsq70yooQzq9gnDmeOC8QMa260ir5ECWxbetyI6I1jmFQ1U2eS6Ofak-9Irum2sD8sKyF5ANUhqzJyBta-n7Q

{
    "reservationDate": "2023-10-29T22:44:00"
}

### cancle reservation
DELETE http://localhost:8080/reservation/cancel/5

### get reservationList (User)
GET http://localhost:8080/reservation/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiYW5hbmEiLCJtZW1iZXJUeXBlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjk4MjEyMDY5LCJleHAiOjE2OTgyMTU2Njl9.bUm_WQ_kCTfyIWnccPRKI1O73Ia3UBPs7V783VqgvEvgdR8QdAL3u8ABn9PNGuSgNYl2XHpB7Vu5JOFxcJOK1A

### get reseravtionList (Partner)
GET http://localhost:8080/reservation/list/2?date=2023-10-29
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcHBsZSIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTg1NTAwMjgsImV4cCI6MTY5ODU1MzYyOH0.GxLT6pqL0TJIOj83QFHS6ZMJ9N9dmY4fTTdEKCHcIfT0WswN5DW51gAirD6ushKdaVVj26zkYVxeSWl89DvhQw

### approve reservation
PATCH http://localhost:8080/reservation/approval/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcHBsZSIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTg1NTAwMjgsImV4cCI6MTY5ODU1MzYyOH0.GxLT6pqL0TJIOj83QFHS6ZMJ9N9dmY4fTTdEKCHcIfT0WswN5DW51gAirD6ushKdaVVj26zkYVxeSWl89DvhQw


### refuse reservation
PATCH http://localhost:8080/reservation/refusal/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZWxvbiIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTgyMTQ5NDQsImV4cCI6MTY5ODIxODU0NH0.25OmK4TMq0VgfMPPQ40Sn50ZfH5OpP4NMNuRaLHCRL25WHRc4onKa2s2EgpcCMHoYNnTtQ4E0khDNDEfHpfk5Q