### regist store
POST http://localhost:8080/store/regist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhcHBsZSIsIm1lbWJlclR5cGUiOiJST0xFX1BBUlRORVIiLCJpYXQiOjE2OTg0NjUxNzQsImV4cCI6MTY5ODQ2ODc3NH0.jIZ9G_nIuBQPtviUOUuAijJ-dA4XVdbO-59S68YhFb4cakKCk9J-ISZ1nZPALEDxX4qDLDqhQzjvcqVUQaw26Q

{
    "name": "기사식당",
    "address": "경기도 이천시",
    "description": "불백은 진리",
    "contact": "031-123-9082",
    "open": "09:00:00",
    "close": "17:00:00"
}

### search store
GET http://localhost:8080/store/search?name=동

### get stores
GET http://localhost:8080/store/list?orderBy=rating

### get store details
GET http://localhost:8080/store/details/9