### signup
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "userId": "banana",
    "password": "2222",
    "userName": "반하나",
    "phone": "010-2222-2222",
    "memberType": "ROLE_USER"
}

### signin
POST http://localhost:8080/user/signin
Content-Type: application/json

{
    "userId": "apple",
    "password": "1111"
}