spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: choco025874
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jwt:
    secret: emVyb2Jhc2VfdGVjaG5pY2FsX2Fzc2lnbm1lbnRfcmVzZXJ2YXRpb25fc2VydmljZV9zZWNyZXRLZXkK=
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher