### signup
POST http://localhost:8080/user/signup
Content-Type: application/json

{
    "userId": "apple",
    "password": "1111",
    "userName": "김사과",
    "phone": "010-1111-1111",
    "roles": [
        "ROLE_PARTNER"
    ]
}

### signin
POST http://localhost:8080/user/signin
Content-Type: application/json

{
    "userId": "apple",
    "password": "1111"
}